# -*- coding: utf-8 -*-
"""convert model to Tflite.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ikruxZS4iL2ZizniXzqFB0IVaSCdMuwa

## Apel
"""

import tensorflow as tf

model = tf.keras.models.load_model('/content/drive/MyDrive/model_project/Model_Apel_Xception.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("modelApel.tflite", "wb").write(tflite_model)

"""## Anggur"""

import tensorflow as tf

model = tf.keras.models.load_model('/content/drive/MyDrive/model_project/Model_Anggur_Xception.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("modelAnggur.tflite", "wb").write(tflite_model)

"""## Jagung"""

import tensorflow as tf

model = tf.keras.models.load_model('/content/drive/MyDrive/model_project/Model_Jagung_Xception.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("modelJagung.tflite", "wb").write(tflite_model)

"""## Kentang"""

import tensorflow as tf

model = tf.keras.models.load_model('/content/drive/MyDrive/model_project/Model_Kentang_Xception.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("modelKentang.tflite", "wb").write(tflite_model)

"""## Padi"""

import tensorflow as tf

model = tf.keras.models.load_model('/content/drive/MyDrive/model_project/Model_Padi_Xception.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("modelPadi.tflite", "wb").write(tflite_model)

"""## Tomat"""

import tensorflow as tf

model = tf.keras.models.load_model('/content/drive/MyDrive/model_project/Model_Tomat_Xception.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("modelTomat.tflite", "wb").write(tflite_model)

"""## Daun"""

import tensorflow as tf

model = tf.keras.models.load_model('/content/drive/MyDrive/model_project/Model_Daun_Xception.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("modelDaun.tflite", "wb").write(tflite_model)

